package com.sentinel.enforcement.application.security;

public enum Permission {
  CREATE_REPORT,
  READ_REPORT,
  TRIAGE_REPORT,
  CREATE_CASE,
  READ_CASE,
  LIST_CASES,
  ASSIGN_CASE,
  TRANSITION_CASE,
  READ_CASE_AUDIT,
  CREATE_EVIDENCE_UPLOAD_SESSION,
  FINALIZE_EVIDENCE,
  READ_EVIDENCE,
  CREATE_EVIDENCE_DOWNLOAD_SESSION,
  LIST_TASKS,
  CLAIM_TASK,
  COMPLETE_TASK,
  RECONCILE_WORKFLOW
}
