package com.sentinel.enforcement.application.workflow;

public enum WorkflowReconciliationIssueType {
  ACTIVE_RUNTIME_MISSING_CORRELATION,
  ACTIVE_RUNTIME_CORRELATION_MISMATCH,
  ACTIVE_CASE_WORKFLOW_NOT_RUNNING,
  ACTIVE_CASE_CORRELATION_TERMINAL,
  TERMINAL_CASE_RUNTIME_ACTIVE,
  TERMINAL_CASE_CORRELATION_ACTIVE,
  TERMINAL_CASE_MISSING_CORRELATION
}
